#!/usr/bin/bash

BIN_NAME="main"
IN_FILE="data/video.rgb24"
OUT_FILE_1="data/encoded.yuv"
OUT_FILE_2="data/decoded.rle"
WIDTH="384"
HEIGHT="216"

rm ${OUT_FILE_1}
rm ${OUT_FILE_2}
rustc ./main.rs && ./${BIN_NAME} ${IN_FILE} ${OUT_FILE_1} ${OUT_FILE_2} ${WIDTH} ${HEIGHT}
